### ISSUE TITLE
Agent state leads to dead agent in crowd.

### ISSUE THREAD

**Issue by mitm001** [MeFisto94/jme3-recast4j-demo#10]
If your agent gets set to 
```
 CrowdAgentState       [DT_CROWDAGENT_STATE_INVALID]
```
which happens when there are no polygons under the agent, like when you set a filter to exclude WALK, and they are on WALK surface, there is no way to reset their CrowdAgentState except by adding to the crowd again....

**Comment by MeFisto94** [comment]
Similarly, if I try to place them on a WALK terrain, AddGridCrowd fails with
```
Caused by: java.lang.NullPointerException
	at org.recast4j.detour.DetourCommon.vCopy(DetourCommon.java:101)
	at org.recast4j.detour.crowd.PathCorridor.reset(PathCorridor.java:201)
	at org.recast4j.detour.crowd.Crowd.addAgent(Crowd.java:389)
	at com.jme3.recast4j.Detour.Crowd.Crowd.createAgent(Crowd.java:99)
```
