### ISSUE TITLE
Selecting Invalid Targets Leads to an NPE

### ISSUE THREAD

**Issue by MeFisto94** [MeFisto94/jme3-recast4j-demo#19]
```
java.lang.NullPointerException
	at org.recast4j.detour.DetourCommon.vCopy(DetourCommon.java:101)
	at org.recast4j.detour.crowd.Crowd.checkPathValidity(Crowd.java:826)
	at org.recast4j.detour.crowd.Crowd.update(Crowd.java:875)
	at com.jme3.recast4j.Detour.Crowd.Crowd.update(Crowd.java:84)
	at com.jme3.recast4j.Detour.Crowd.CrowdManager.lambda$update$0(CrowdManager.java:78)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.jme3.recast4j.Detour.Crowd.CrowdManager.update(CrowdManager.java:78)
	at com.jme3.recast4j.Detour.Crowd.Impl.CrowdManagerAppstate.update(CrowdManagerAppstate.java:48)
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:303)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:253)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:748)
```

is thrown when the fish try to swim outside of the pond

Edit: So this is something probably relevant to recast4j as the Crowd should try to fall back when a target is invalid. We _could_ try to prevent illegal requestMoveToTargets on our side, but I'm not sure whether we can apply filters on our own. (targetPoly != 0 isn't enough here)

Maybe we could work around it by selecting the right filters here: https://github.com/MeFisto94/jme3-recast4j-demo/blob/master/src/main/java/com/jme3/recast4j/demo/states/tutorial/CrowdState.java#L383

On the other hand Crowd should now it's query filters, right?
Edit2: So I checked it, it has to be done in https://github.com/MeFisto94/jme3-recast4j/blob/master/src/main/java/com/jme3/recast4j/Detour/Crowd/Crowd.java#L243
But which of the n filters to pick? If I got that right I can have multiple filters at the same time? but which one is active?

Sooo one can use getFilter(i) from 0 to `DT_CROWD_MAX_QUERY_FILTER_TYPE = 16`, but I guess one can only use one filter at a time, so maybe there is an index which is the active filter.

Edit3: Crowd Uses m_filters[ag.params.queryFilterType]

**Comment by MeFisto94** [comment]
Unfortunately https://github.com/MeFisto94/jme3-recast4j/commit/64ea74030507b26356416cb83c4eaa93a25e47b2 doesn't fix this, because public boolean requestMoveToTarget(Vector3f to, long polyRef) is called and since it already has a polyRef it cannot use the filters. This means validation has to be done on -demo side as well.

The Problem with this only is, that the current filter is a _agent-local_ setting, not a crowd-local one, so that is a bit problematic for a crowd as a whole...

**Comment by MeFisto94** [comment]
Closing, I should've written "Fixes" instead of Fixing for Auto-Close to work :man_facepalming:
